### ISSUE TITLE
undefined <access-token-pending>

### ISSUE THREAD

**Issue by denizdogan** [tostringtheory/insomnia-plugin-accesstoken#1]
I can't seem to figure out how to use this plugin properly. Whenever I preview the token it says `undefined <access-token-pending>`. If I go ahead and try to execute a request using this it says "The access token is missing".

Just to be clear, this plugin expects the access token response to be formatted like this, right?

```json
{
  "access_token": ".......",
  "expires_in": 300,
  "token_type": "Bearer"
}
```

Any ideas?

**Comment by tostringtheory** [comment]
This plugin specifically gathers the Access Token from a Requests' OAuth configuration (https://support.insomnia.rest/article/38-authentication).  

It sounds like you have defined a manual request not using the built in OAuth settings for a request, and therefore the Prefix it gathers is 'undefined' and the token is eternally pending.  You COULD leave your setup the way you have it, and use the response tag to grab the value from the response JSON; or you could change your request to utilize the inbuilt OAuth Authentication settings.

**Comment by denizdogan** [comment]
I'm not entirely sure I follow, with this OAuth2 provider, I need to first get the access token using a request with Basic authentication, then the response will contain the OAuth2 access token which I can use for the subsequent requests.

So my request to fetch the access token looks like this:

![image](https://user-images.githubusercontent.com/50928/71987314-45411900-322e-11ea-8187-36542f239dff.png)

Did I misunderstand the entire point of this plugin? :)

**Comment by tostringtheory** [comment]
Ah - I see what's wrong now.  You ARE using the built in Authentication mechanism, but you're NOT using the built in OAuth 2 authentication mechanism - which is where Insomnia executes/stores the access token for you.

Where you have "Basic" selected, change that to OAuth 2, since you're authenticating with an OAuth 2 provider.  For the type you'll need to select Client Credentials it appears (since you're referencing client_id/client_secret).  Fill out any of the remaining fields as needed, then at the bottom of the OAuth pane, click "Fetch Tokens", at which point it will execute and store the tokens, and then this plugin will utilize them.

I'm not at my PC right now so can't gather a screenshot and am doing this from memory, but that should get you just about setup.

**Comment by denizdogan** [comment]
Awesome, it seems like I managed to do it!

In case anyone has the same problem, this is what my authentication request looks like now:

![image](https://user-images.githubusercontent.com/50928/71988966-14aeae80-3231-11ea-8b34-0a000a049c9a.png)

(Just click "Fetch Token" at the bottom, don't try to execute the request itself. This confused me a lot.)

And this is what my (authenticated) request looks like:

![image](https://user-images.githubusercontent.com/50928/71989002-22fcca80-3231-11ea-8020-85a262d4ca62.png)

Thank you, @tostringtheory !

**Comment by tostringtheory** [comment]
@denizdogan - might I suggest looking into the `insomnia-plugin-default-headers` plugin?  It allows you to defined an object in your environments (base or otherwise) and then specify 1 or more headers to be sent on all requests:

![image](https://user-images.githubusercontent.com/2874305/71992978-f2e70480-31fb-11ea-845e-002ab185092a.png)

I suggest this because I see you're using the `Bearer` auth setup, which means you'd have to setup every other request with this configuration as well.  If you use the default headers plugin, then you'd be able to just set it in 1 place and be done.  This definitely depends on your use case, but it's what we're doing internally without any friction, so wanted to suggest it.

You were also correct in that you aren't sending the actual request when Fetching tokens, just the request.  You could leave the request URL empty, or set it to an authenticated URI.  I have mine set to the base/host of the API.

**Comment by denizdogan** [comment]
@tostringtheory Yup, already started looking at default headers, seems easy enough :) Thanks again
